apiVersion: v1
kind: Service # Expose the pods to the outside of the cluster
metadata:
  name: app1
spec:
  selector: # Links the service to a kubernetes ressources
    app: app1
  ports:
  - protocol: TCP
    port: 80  # Expose ports
    targetPort: 8080 # Router ports
  
--- # separate ressources

apiVersion: apps/v1
kind: Deployment # Manages the lifecycle of the application's pods, ensuring one replica runs at all times.
metadata:
  name: app1
  labels:
    app: app1
spec:
  replicas: 1 # replica of pods for scalability
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1 #pods ID
    spec:
      containers:
      - name: hello-kubernetes
        image: paulbouwer/hello-kubernetes:1.10
        env:
        - name: MESSAGE
          value: "Hello from app1"
        ports:
        - containerPort: 8080