Vagrant.configure("2") do |config|
	config.vm.box = "debian/bullseye64"
  
	#Serveur
	config.vm.define "acharlotS" do |server|
	  server.vm.hostname = "acharlotS"
	  server.vm.synced_folder "./confs", "/vagrant/confs/"
	  server.vm.network "private_network", ip: "192.168.56.110"
	  server.vm.provider "virtualbox" do |vb|
		vb.memory = 1024
		vb.cpus = 1
		vb.name = "acharlotS"
	  end
	  server.vm.provision "shell", path: "scripts/setup.sh"
	end

  end
  