Vagrant.configure("2") do |config|
  config.vm.box = "debian/bullseye64"

  #Serveur
  config.vm.define "acharlotS" do |server|
    server.vm.hostname = "acharlotS"
    server.vm.network "private-network", ip: "192.168.56.110"
    server.vm.provider "virtualbox" do |vb|
      vb.memory = 2048
      vb.cpus = 2
      vb.name = "acharlotS"
    end
    server.vm.provision "shell", path: "scripts/server_install.sh", args: "> /vagrant/logs/server.log 2>&1" #combine the stderr and stdout into a single file in the /vagrant/logs folder on the host machine.
  end

  #Worker
  config.vm.define "acharlotSW" do |worker|
    worker.vm.hostname = "acharlot"
    worker.vm.network "private_network", ip: "192.168.56.111"
    worker.vm.provider "virtualbox" do |vb|
      vb.memory = 2048
      vb.cpus = 2
      vb.name = "acharlotSW"
    end
    worker.vm.provision "shell", path: "scripts/agent_install.sh", args: "> /vagrant/logs/worker.log 2>&1"
  end
end
