Vagrant.configure("2") do |config|
  config.vm.box = "debian/bullseye64"

  #Serveur
  config.vm.define "acharlotS" do |server|
    server.vm.hostname = "acharlotS"
    server.vm.network "private_network", ip: "192.168.56.110"
    server.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
      vb.cpus = 1
      vb.name = "acharlotS"
    end
    server.vm.provision "shell", path: "scripts/server_install.sh"
  end

  #Worker
  config.vm.define "acharlotSW" do |worker|
    worker.vm.hostname = "acharlotSW"
    worker.vm.network "private_network", ip: "192.168.56.111"
    worker.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
      vb.cpus = 1
      vb.name = "acharlotSW"
    end
    worker.vm.provision "shell", path: "scripts/agent_install.sh"
  end
end
